# Generated by Django 5.2 on 2025-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cca2', models.CharField(max_length=3)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('timezones', models.JSONField()),
                ('languages', models.JSONField()),
                ('flag', models.URLField()),
            ],
        ),
    ]
